name: VaultVoucher
version: '1.0'
main: com.example.main.vaultvoucher.VaultVoucher
api-version: '1.21'
load: POSTWORLD
author: Mike4947
description: to convert their in-game money into physical voucher items

# Hard dependency - Required for the plugin to function at all.
depend: [Vault]

log-prefix: VAULT-VOUCHER

commands:
  voucher:
    description: Creates a physical voucher from your account balance.
    usage: "/voucher <amount>"
    permission: vaultvoucher.create

permissions:
  vaultvoucher.create:
    description: Allows players to create vouchers.
    default: true
  vaultvoucher.redeem:
    description: Allows players to redeem vouchers.
    default: true